### ISSUE TITLE
How to handle starting the section numbering at 0?

### ISSUE THREAD

**Issue by Sinthoras7** [jbirnick/typst-headcount#2]
I made a similar issue on the rich counters package. https://github.com/jbirnick/typst-rich-counters/issues/3

I want to use this package to get my equation numbering dependent on the current section. For that theoretically I would prefer to use headcount to rich counters, because with it, the native equation counter is used, and I don't have to create a new one and manually add the show rules to update it appropriately, which is cleaner. 

But the solution from the other issue, namely
```typst
set math.equation(numbering: (fst, ..nums) => dependent-numbering("(1.1)", levels: 1)(fst - 1, ..nums))
```
does not work in headcount.

Is there another way to handle it, or should I just not use this package for that goal?

**Comment by jbirnick** [comment]
`dependent-numbering` works like a wrapper in which you put what you put "usually". So the analog of https://github.com/jbirnick/typst-rich-counters/issues/3 would be this:

```typ
#import "@preview/headcount:0.1.0": *
#import "@preview/numbly:0.1.0": *

#set heading(numbering: "1.1")
#show heading: reset-counter(counter(math.equation))
#set math.equation(numbering: dependent-numbering((fst, ..nums) => numbly("Top {1}:", "{1}.{2}")(fst - 1, ..nums)))

= Some Heading

$ x $

$ y $

= Another Heading

$ z $
```

**Comment by Sinthoras7** [comment]
Thank you for the quick response!
